baseURL: "https://girorme.github.io/"
theme: "writeonlyhugo-theme"

defaultContentLanguage: pt
defaultContentLanguageInSubdir: false
languages:
  pt:
    contentDir: content
    disabled: false
    languageCode: pt-BR
    languageDirection: ltr
    languageName: Portugues
    params:
      subtitle: Teste1, Teste2 e Teste3
    title: Girorme's blog
    weight: 1
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Test1, Test2, and Test3
    title: Girorme's blog
    weight: 2

title: "Girorme's blog"

googleAnalytics: "G-SHV963YSF5"

summaryLength: 20

params:
  contentDir: "content"
  title: "Girorme's blog"
  description: "Misc blog! Writing about a lot of topics, including: programming, sec, psicology and more"
  images: 
    - "images/avatar.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  contact:
    - "g1r0rm3@gmail.com"

  copyright: "© 2024 Girorme - All Rights Reserved"

menus:
  main:
    - name: EN
      url: "/en"
      weight: 1

    - name: PT
      url: "/"
      weight: 2

    - name: "Home"
      url: "/"
      weight: 3

    - name: "About"
      url: "/about"
      weight: 4

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About"
      url: "/#"
      weight: 2
      
taxonomies:
  series: "series"
  tags: "tags"
  categories: "categories"

module:
  mounts:
    - source: 'images'
      target: 'static/images'
